name: 'ci'

on:
  push:

env:
  PROJECT_ID: 'my-project'
  # '${{ env.PROJECT_ID }}'

jobs:
  ci:
    name: 'Setup, Build and Test'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run -F ext build
